#!/bin/bash

#rm -rf freeboard


if ls freeboard >> /dev/null ; then echo found freeboard directory... not running git clone
else
 git clone https://github.com/Freeboard/freeboard.git
fi

#exit

cp widget.rest.button.js freeboard/plugins/thirdparty/
ls freeboard/plugins/thirdparty/widget.rest.button.js

cp exmaple.json freeboard/example.json

echo -e "\n<script>head.js('plugins/thirdparty/widget.rest.button.js',()=>{})</script>" >> freeboard/index.html

#start

screen -dmS pythonServer python -m SimpleHTTPServer 8888

if [ $(uname) = "Linux" ]
then
	xdg-open freeboard/index.html
	xdg-open http://localhost:8888/freeboard/index.html?load=example.json
else
	open freeboard/index.html
	open http://localhost:8888/freeboard/index.html?load=example.json
fi


sleep 600
pkill screen
